# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: c:/users/computer/vivado_project/ip_repo/vga640x480_1.0/bd/vga_buff/vga_buff_ooc.xdc

# XDC: c:/users/computer/vivado_project/ip_repo/vga640x480_1.0/vga640x480_v1_0/vga640x480_v1_0.srcs/sources_1/bd/design_1/design_1_ooc.xdc

# IP: c:/users/computer/vivado_project/ip_repo/vga640x480_1.0/vga640x480_v1_0/vga640x480_v1_0.srcs/sources_1/bd/design_1/ip/design_1_blk_mem_gen_0_0/design_1_blk_mem_gen_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_blk_mem_gen_0_0 || ORIG_REF_NAME==design_1_blk_mem_gen_0_0}]

# XDC: c:/users/computer/vivado_project/ip_repo/vga640x480_1.0/vga640x480_v1_0/vga640x480_v1_0.srcs/sources_1/bd/design_1/ip/design_1_blk_mem_gen_0_0/design_1_blk_mem_gen_0_0_ooc.xdc
