# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
set_msg_config -id {HDL-1065} -limit 10000
create_project -in_memory -part xc7z020clg484-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir c:/users/computer/vivado_project/ps_vga/ps_vga.tmp/vga640x480_v1_0_project/vga640x480_v1_0_project.cache/wt [current_project]
set_property parent.project_path c:/users/computer/vivado_project/ps_vga/ps_vga.tmp/vga640x480_v1_0_project/vga640x480_v1_0_project.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part em.avnet.com:zed:part0:1.3 [current_project]
set_property ip_repo_paths c:/users/computer/vivado_project/ip_repo/vga640x480_1.0 [current_project]
set_property vhdl_version vhdl_2k [current_fileset]
add_files c:/Users/Computer/VIVADO_project/PS_VGA/PS_VGA.srcs/sources_1/bmp_init.coe
read_ip c:/users/computer/vivado_project/ip_repo/vga640x480_1.0/vga640x480_v1_0/vga640x480_v1_0.srcs/sources_1/bd/design_1/ip/design_1_blk_mem_gen_0_0/design_1_blk_mem_gen_0_0.xci
set_property used_in_implementation false [get_files -all c:/users/computer/vivado_project/ip_repo/vga640x480_1.0/vga640x480_v1_0/vga640x480_v1_0.srcs/sources_1/bd/design_1/ip/design_1_blk_mem_gen_0_0/design_1_blk_mem_gen_0_0_ooc.xdc]
set_property is_locked true [get_files c:/users/computer/vivado_project/ip_repo/vga640x480_1.0/vga640x480_v1_0/vga640x480_v1_0.srcs/sources_1/bd/design_1/ip/design_1_blk_mem_gen_0_0/design_1_blk_mem_gen_0_0.xci]

read_verilog -library xil_defaultlib {
  c:/users/computer/vivado_project/ip_repo/vga640x480_1.0/vga640x480_v1_0/vga640x480_v1_0.srcs/sources_1/bd/design_1/hdl/design_1.v
  c:/users/computer/vivado_project/ip_repo/vga640x480_1.0/vga640x480_v1_0/vga640x480_v1_0.srcs/sources_1/bd/design_1/hdl/design_1_wrapper.v
  c:/users/computer/vivado_project/ip_repo/vga640x480_1.0/bd/vga_buff/hdl/vga_buff_wrapper.v
  c:/users/computer/vivado_project/ip_repo/vga640x480_1.0/src/my_vga_syn.v
  c:/users/computer/vivado_project/ip_repo/vga640x480_1.0/src/vga_drv.v
  c:/users/computer/vivado_project/ip_repo/vga640x480_1.0/hdl/vga640x480_v1_0_S00_AXI.v
  c:/users/computer/vivado_project/ip_repo/vga640x480_1.0/hdl/vga640x480_v1_0.v
}
read_xdc -mode out_of_context c:/users/computer/vivado_project/ip_repo/vga640x480_1.0/bd/vga_buff/vga_buff_ooc.xdc
set_property used_in_implementation false [get_files c:/users/computer/vivado_project/ip_repo/vga640x480_1.0/bd/vga_buff/vga_buff_ooc.xdc]

read_xdc -mode out_of_context c:/users/computer/vivado_project/ip_repo/vga640x480_1.0/vga640x480_v1_0/vga640x480_v1_0.srcs/sources_1/bd/design_1/design_1_ooc.xdc
set_property used_in_implementation false [get_files c:/users/computer/vivado_project/ip_repo/vga640x480_1.0/vga640x480_v1_0/vga640x480_v1_0.srcs/sources_1/bd/design_1/design_1_ooc.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
synth_design -top vga640x480_v1_0 -part xc7z020clg484-1
write_checkpoint -noxdef vga640x480_v1_0.dcp
catch { report_utilization -file vga640x480_v1_0_utilization_synth.rpt -pb vga640x480_v1_0_utilization_synth.pb }
