# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7z020clg484-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Users/Computer/VIVADO_project/PS_VGA/PS_VGA.cache/wt [current_project]
set_property parent.project_path C:/Users/Computer/VIVADO_project/PS_VGA/PS_VGA.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part em.avnet.com:zed:part0:1.3 [current_project]
set_property ip_repo_paths {
  c:/Users/Computer/VIVADO_project/ip_repo/vga640x480_1.0
  c:/Users/Computer/VIVADO_project/ip_repo/rgb2dvi
  c:/Users/Computer/VIVADO_project/ip_repo/axi_dynclk_v1_0
} [current_project]
set_property vhdl_version vhdl_2k [current_fileset]
add_files C:/Users/Computer/VIVADO_project/PS_VGA/PS_VGA.srcs/sources_1/bd/design_1/design_1.bd
set_property used_in_implementation false [get_files -all c:/Users/Computer/VIVADO_project/PS_VGA/PS_VGA.srcs/sources_1/bd/design_1/ip/design_1_rst_processing_system7_0_50M_0/design_1_rst_processing_system7_0_50M_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Computer/VIVADO_project/PS_VGA/PS_VGA.srcs/sources_1/bd/design_1/ip/design_1_rst_processing_system7_0_50M_0/design_1_rst_processing_system7_0_50M_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Computer/VIVADO_project/PS_VGA/PS_VGA.srcs/sources_1/bd/design_1/ip/design_1_rst_processing_system7_0_50M_0/design_1_rst_processing_system7_0_50M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Computer/VIVADO_project/PS_VGA/PS_VGA.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_0_0/design_1_clk_wiz_0_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Computer/VIVADO_project/PS_VGA/PS_VGA.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_0_0/design_1_clk_wiz_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Computer/VIVADO_project/PS_VGA/PS_VGA.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_0_0/design_1_clk_wiz_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Computer/VIVADO_project/PS_VGA/PS_VGA.srcs/sources_1/bd/design_1/ip/design_1_vga640x480_v1_1_0_1/bd/vga_buff/ip/vga_buff_blk_mem_gen_0_0/vga_buff_blk_mem_gen_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Computer/VIVADO_project/PS_VGA/PS_VGA.srcs/sources_1/bd/design_1/ip/design_1_vga640x480_v1_1_0_1/bd/vga_buff/vga_buff_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Computer/VIVADO_project/PS_VGA/PS_VGA.srcs/sources_1/bd/design_1/ip/design_1_processing_system7_0_1/design_1_processing_system7_0_1.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Computer/VIVADO_project/PS_VGA/PS_VGA.srcs/sources_1/bd/design_1/ip/design_1_auto_pc_0/design_1_auto_pc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all C:/Users/Computer/VIVADO_project/PS_VGA/PS_VGA.srcs/sources_1/bd/design_1/design_1_ooc.xdc]
set_property is_locked true [get_files C:/Users/Computer/VIVADO_project/PS_VGA/PS_VGA.srcs/sources_1/bd/design_1/design_1.bd]

read_verilog -library xil_defaultlib C:/Users/Computer/VIVADO_project/PS_VGA/PS_VGA.srcs/sources_1/bd/design_1/hdl/design_1_wrapper.v
read_xdc C:/Users/Computer/VIVADO_project/PS_VGA/PS_VGA.srcs/constrs_1/new/pins.xdc
set_property used_in_implementation false [get_files C:/Users/Computer/VIVADO_project/PS_VGA/PS_VGA.srcs/constrs_1/new/pins.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
synth_design -top design_1_wrapper -part xc7z020clg484-1
write_checkpoint -noxdef design_1_wrapper.dcp
catch { report_utilization -file design_1_wrapper_utilization_synth.rpt -pb design_1_wrapper_utilization_synth.pb }
